@echo off
echo Refreshing network...
ipconfig /release
ipconfig /renew
ipconfig /flushdns
echo Restarting Windows Explorer...
taskkill /f /im explorer.exe
start explorer.exe
echo Clearing temporary files...
del /q /f /s %TEMP%\*
echo Restarting computer...
shutdown /r /t 0